Class = require("lib/class")

require("src/Constants")
require("src/Utils")
require("src/StateMachine")
require("src/States/BaseState")
require("src/States/PlayState")
require("src/States/ScoreState")

require("src/Block")
require("src/Tetrominoes/BaseTetromino")
require("src/Tetrominoes/LTetromino")
require("src/Tetrominoes/OTetromino")
require("src/Tetrominoes/TTetromino")
require("src/Tetrominoes/ITetromino")
require("src/Tetrominoes/ZTetromino")
require("src/Tetrominoes/Tetrominoes")